# Generated by Django 2.2 on 2021-03-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210327_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
